# Site settings
title: State of the Map LATAM 2024
email: info@osmlatam.org
description: 
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Semper aeterno percipit ut his, sea ex utinam referrentur repudiandae. Ei qui diceret voluptua luptatum, te dolorum detracto hendrerit sed, ad per offendit consetetur. No epicuri hendrerit consetetur sit, sit dicta adipiscing ex, in facete detracto deterruisset duo. Scripta periculis ei eam, te pro movet reformidans. Vivendum intellegat et qui, ei denique consequuntur vix. Scripta periculis ei eam, te pro movet reformidans. Scripta periculis ei eam, te pro movet reformidans. Quot populo ad qui. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Eos ex affert fabulas iudicabit, dolore ornatus instructior ex per.
url: "https://2024.osmlatam.org/" 
baseurl: "" 
email: "state@osmlatam.org"
facebook_page: "osmlatam"
twitter_username: "osmlatam"
github_username:
website: "https://2024.osmlatam.org/"
exclude: [README.md]

registrations:
  open: true
  url: https://doity.com.br/sotm-latam-bra-2024

program: 
  proposals: 
    open: false
    url: https://pretalx.com/sotm-latam-bra-2024/cfp
  schedule:
    ready: false
    url: https://pretalx.com/sotm-latam-bra-2024/schedule
  

# Build settings
markdown: kramdown

# Venue
map_config:
  coordinates: [-1.43792, -48.46148] # Latitude, Longitude
  zoom_level: 18


# Translations
t:
  en:
    language_name: English
    modal:
      abstract: Abstract
      close: Close
    menu:
      about:
        label: About
        url: /en/#about
      program:
        label: Program
        url: /en/#program
      sponsors:
        label: Sponsors
        url: /en/#sponsors
      access:
        label: How to get there
        url: /en/#access
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "The Latin American OpenStreetMap Conference"
      location: "Belém, Brazil"
      dates: "December 7 and 8, 2024"
      registrations_button: "Register Now"
      submit_proposal: "Submit Your Proposal"
    venue_section:
      title: "Venue"
      place_name: "Instituto Federal do Pará (IFPA)"
      description: "Vivamus aliquet dignissim sapien, semper venenatis massa sagittis dictum. Mauris in magna rutrum, tristique est quis, venenatis nisl. Sed quis nibh nulla. Praesent eu volutpat urna. Maecenas venenatis, augue sed aliquam luctus, nibh lectus pellentesque magna, at egestas eros nisi sit amet lacus. In hac habitasse platea dictumst."
  es:
    language_name: Español
    modal:
      abstract: Ver resumen
      close: Cerrar
    menu:
      about:
        label: Acerca de
        url: /es/#about
      program:
        label: Programa
        url: /es/#program
      sponsors:
        label: Patrocinadores
        url: /es/#sponsors
      access:
        label: Cómo llegar
        url: /es/#access
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "La conferencia latinoamericana de OpenStreetMap"
      location: "Belém, Brasil"
      dates: "7 y 8 de diciembre, 2024"
      registrations_button: "Inscripciones"
      submit_proposal: "Envía tu Ponencia"
    venue_section:
      title: "Lugar"
      place_name: "Instituto Federal do Pará (IFPA)"
      description: "Vivamus aliquet dignissim sapien, semper venenatis massa sagittis dictum. Mauris in magna rutrum, tristique est quis, venenatis nisl. Sed quis nibh nulla. Praesent eu volutpat urna. Maecenas venenatis, augue sed aliquam luctus, nibh lectus pellentesque magna, at egestas eros nisi sit amet lacus. In hac habitasse platea dictumst."
  pt:
    language_name: Português
    modal:
      abstract: Ver resumo
      close: Fechar
    menu:
      about:
        label: Sobre
        url: /pt/#about
      program:
        label: Programa
        url: /pt/#program
      sponsors:
        label: Patrocinadores
        url: /pt/#sponsors
      access:
        label: Como Chegar
        url: /pt/#access
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "A conferência latino-americana de OpenStreetMap"
      location: "Belém, Brasil"
      dates: "7 e 8 de dezembro de 2024"
      registrations_button: "Inscreva-se"
      submit_proposal: "Envie sua atividade"        
    venue_section:
      title: "Local"
      place_name: "Instituto Federal do Pará (IFPA)"
      description: "Vivamus aliquet dignissim sapien, semper venenatis massa sagittis dictum. Mauris in magna rutrum, tristique est quis, venenatis nisl. Sed quis nibh nulla. Praesent eu volutpat urna. Maecenas venenatis, augue sed aliquam luctus, nibh lectus pellentesque magna, at egestas eros nisi sit amet lacus. In hac habitasse platea dictumst."
      

