# Site settings
title: State of the Map LATAM 2024
author: OpenStreetMap Latam
email: info@osmlatam.org
contact_form_url:
  pt: https://forms.gle/Ky19ce58sBeQt3rM6
  en: https://forms.gle/bmoEfEsVwoJ31aFA9
  es: https://forms.gle/v26G3sVFZ4o6At4Y8
baseurl: ""
website: "https://2024.osmlatam.org"
exclude: [README.md]

social:
  facebook:
    title: "Facebook"
    url: "https://www.facebook.com/osmlatam"
    icon: "fab fa-facebook"
  twitter:
    title: "Twitter"
    handle: "@osmlatam"
    url: "https://twitter.com/osmlatam"
    icon: "fab fa-twitter"
  youtube:
    title: "YouTube"
    url: "https://www.youtube.com/channel/UCzYgQtCudy1ihZYAlpC3EXQ"
    icon: "fab fa-youtube"
  linkedin:
    title: "LinkedIn"
    url: "https://www.linkedin.com/company/103151706/"
    icon: "fab fa-linkedin"

registrations:
  open: true
  url: https://doity.com.br/sotm-latam-bra-2024

program:
  stage: call-for-proposals-will-open-soon
  # stage: call-for-proposals-open
  # stage: call-for-proposals-closed
  # stage: program-is-ready
  url: https://pretalx.com/sotm-latam-bra-2024

# Build settings
markdown: kramdown

# Venue
map_config:
  coordinates: [-1.43792, -48.46148] # Latitude, Longitude
  zoom_level: 18

# Translations
t:
  en:
    language_name: English
    description: "Join the OpenStreetMap Latin American community in the Amazon city of Belém do Pará from December 6-8, 2024, to discuss projects, share ideas, and strengthen our network."
    modal:
      abstract: Abstract
      close: Close
    menu:
      about:
        label: About
        url: /en/#about
      program:
        label: Program
        url: /en/#program
      sponsors:
        label: Sponsors
        url: /en/#sponsors
      access:
        label: How to get there
        url: /en/#access
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "The Latin American OpenStreetMap Conference"
      location: "Belém, Brazil"
      dates: "December 6-8, 2024"
      registrations_button: "Register Now"
      submit_proposal: "Submit Your Proposal"
      view_program: "View Program"
    program_section:
      title: "Program"
      call_for_proposals_will_open_soon: "The call for activities will open soon!"
      call_for_proposals_open: "Call for proposals is open!"
      submit_your_proposal: "Submit your proposal"
      thank_you_submissions: "The submission of proposals is closed. The program committee is reviewing the submissions and we will announce the program soon."
      program_is_finalized: "Our program is finalized! Check out the complete schedule to plan your conference experience."
      view_program: "View Program"
    sponsor_section:
      sponsors_title: "Sponsorships"
      sponsors_description: "Become a sponsor and gain direct access to a vibrant community of IT professionals, geographers, students, and other industry experts. This is an excellent opportunity to increase the visibility of your company and create valuable connections. For more information about sponsorship packages, please fill out our contact form."
      contact_button: "Talk to Us"

    venue_section:
      title: "Venue"
      place_name: "Instituto Federal do Pará (IFPA)"
      description: "Vivamus aliquet dignissim sapien, semper venenatis massa sagittis dictum. Mauris in magna rutrum, tristique est quis, venenatis nisl. Sed quis nibh nulla. Praesent eu volutpat urna. Maecenas venenatis, augue sed aliquam luctus, nibh lectus pellentesque magna, at egestas eros nisi sit amet lacus. In hac habitasse platea dictumst."
  es:
    language_name: Español
    description: "Únete a la comunidad de OpenStreetMap Latinoamérica en la ciudad amazónica de Belém do Pará, del 6 al 8 de diciembre de 2024, para discutir proyectos, compartir ideas y fortalecer nuestra red."
    modal:
      abstract: Ver resumen
      close: Cerrar
    menu:
      about:
        label: Acerca de
        url: /#about
      program:
        label: Programa
        url: /#program
      sponsors:
        label: Patrocinadores
        url: /#sponsors
      access:
        label: Cómo llegar
        url: /#access
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "La conferencia latinoamericana de OpenStreetMap"
      location: "Belém, Brasil"
      dates: "6, 7 y 8 de diciembre, 2024"
      registrations_button: "Inscripciones"
      submit_proposal: "Envía tu Ponencia"
      view_program: "Ver Program"
    program_section:
      title: "Programa"
      call_for_proposals_will_open_soon: "La convocatoria de actividades se abrirá pronto!"
      call_for_proposals_open: "¡La convocatoria de propuestas está abierta!"
      submit_your_proposal: "Envía tu propuesta"
      thank_you_submissions: "El envío de propuestas ha terminado. El comité del programa está revisando las propuestas y pronto anunciaremos el programa."
      program_is_finalized: "¡Nuestro programa está finalizado! Consulta el cronograma completo para planificar tu experiencia en la conferencia."
      view_program: "Ver Programa"
    sponsor_section:
      sponsors_title: "Patrocinios"
      sponsors_description: "Conviértase en patrocinador y obtenga acceso directo a una comunidad vibrante de profesionales de TI, geógrafos, estudiantes y otros expertos del sector. Esta es una excelente oportunidad para aumentar la visibilidad de su empresa y crear conexiones valiosas. Para más información sobre los paquetes de patrocinio, por favor, complete nuestro formulario de contacto."
      contact_button: "Hable con nosotros"

    venue_section:
      title: "Lugar"
      place_name: "Instituto Federal do Pará (IFPA)"
      description: "Vivamus aliquet dignissim sapien, semper venenatis massa sagittis dictum. Mauris in magna rutrum, tristique est quis, venenatis nisl. Sed quis nibh nulla. Praesent eu volutpat urna. Maecenas venenatis, augue sed aliquam luctus, nibh lectus pellentesque magna, at egestas eros nisi sit amet lacus. In hac habitasse platea dictumst."
  pt:
    language_name: Português
    description: "Reúna-se com a comunidade de OpenStreetMap da América Latina na cidade amazônica de Belém do Pará, de 6 a 8 de dezembro de 2024, para discutir projetos, compartilhar ideias e fortalecer nossa rede."
    modal:
      abstract: Ver resumo
      close: Fechar
    menu:
      about:
        label: Sobre
        url: /pt/#about
      program:
        label: Programa
        url: /pt/#program
      sponsors:
        label: Patrocinadores
        url: /pt/#sponsors
      access:
        label: Como Chegar
        url: /pt/#access
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "A conferência latino-americana de OpenStreetMap"
      location: "Belém, Brasil"
      dates: "6, 7 e 8 de dezembro de 2024"
      registrations_button: "Inscreva-se"
      submit_proposal: "Envie sua atividade"
      view_program: "Ver Programa"
    program_section:
      title: "Programa"
      call_for_proposals_will_open_soon: "A chamada de atividades será aberta em breve!"
      call_for_proposals_open: "Chamada de propostas está aberta!"
      submit_your_proposal: "Envie sua proposta"
      thank_you_submissions: "O envio de propostas está encerrado. O comitê de programa está revisando as propostas e, em breve, divulgaremos o programa."
      program_is_finalized: "Nosso programa está finalizado! Veja o cronograma completo para planejar sua experiência na conferência."
      view_program: "Visualizar Programa"
    sponsor_section:
      sponsors_title: "Patrocínios"
      sponsors_description: "Torne-se um patrocinador e obtenha acesso direto a uma comunidade vibrante de profissionais de TI, geógrafos, estudantes e outros especialistas do setor. Esta é uma excelente oportunidade para aumentar a visibilidade da sua empresa e criar conexões valiosas. Para mais informações sobre os pacotes de patrocínio, por favor, preencha nosso formulário de contato."
      contact_button: "Fale conosco"
    venue_section:
      title: "Local"
      place_name: "Instituto Federal do Pará (IFPA)"
      description: "Vivamus aliquet dignissim sapien, semper venenatis massa sagittis dictum. Mauris in magna rutrum, tristique est quis, venenatis nisl. Sed quis nibh nulla. Praesent eu volutpat urna. Maecenas venenatis, augue sed aliquam luctus, nibh lectus pellentesque magna, at egestas eros nisi sit amet lacus. In hac habitasse platea dictumst."
