# Site settings
title: State of the Map LATAM 2024
author: OpenStreetMap Latam
email: info@osmlatam.org
url: "https://2024.osmlatam.org/"
baseurl: ""
website: "https://2024.osmlatam.org/"
exclude: [README.md]

social:
  facebook:
    title: "Facebook"
    url: "https://www.facebook.com/osmlatam"
    icon: "fab fa-facebook"
  twitter:
    title: "Twitter"
    handle: "@osmlatam"
    url: "https://twitter.com/osmlatam"
    icon: "fab fa-twitter"
  youtube:
    title: "YouTube"
    url: "https://www.youtube.com/channel/UCzYgQtCudy1ihZYAlpC3EXQ"
    icon: "fab fa-youtube"
  linkedin:
    title: "LinkedIn"
    url: "https://www.linkedin.com/company/103151706/"
    icon: "fab fa-linkedin"

registrations:
  open: true
  url: https://doity.com.br/sotm-latam-bra-2024

program:
  proposals:
    open: false
    url: https://pretalx.com/sotm-latam-bra-2024/cfp
  schedule:
    ready: false
    url: https://pretalx.com/sotm-latam-bra-2024/schedule

# Build settings
markdown: kramdown

# Venue
map_config:
  coordinates: [-1.43792, -48.46148] # Latitude, Longitude
  zoom_level: 18

# Translations
t:
  en:
    language_name: English
    description: "Join us for the State of the Map LATAM 2024 in Belém, Brazil on December 7-8, 2024. Engage with experts and enthusiasts from across Latin America in this vibrant conference dedicated to fostering open mapping and innovative geospatial technologies."
    modal:
      abstract: Abstract
      close: Close
    menu:
      about:
        label: About
        url: /en/#about
      program:
        label: Program
        url: /en/#program
      sponsors:
        label: Sponsors
        url: /en/#sponsors
      access:
        label: How to get there
        url: /en/#access
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "The Latin American OpenStreetMap Conference"
      location: "Belém, Brazil"
      dates: "December 7 and 8, 2024"
      registrations_button: "Register Now"
      submit_proposal: "Submit Your Proposal"
    program_section:
      title: "Program"
      description: "Vivamus aliquet dignissim sapien, semper venenatis massa sagittis dictum. Mauris in magna rutrum, tristique est quis, venenatis nisl. Sed quis nibh nulla. Praesent eu volutpat urna. Maecenas venenatis, augue sed aliquam luctus, nibh lectus pellentesque magna, at egestas eros nisi sit amet lacus. In hac habitasse platea dictumst."
    venue_section:
      title: "Venue"
      place_name: "Instituto Federal do Pará (IFPA)"
      description: "Vivamus aliquet dignissim sapien, semper venenatis massa sagittis dictum. Mauris in magna rutrum, tristique est quis, venenatis nisl. Sed quis nibh nulla. Praesent eu volutpat urna. Maecenas venenatis, augue sed aliquam luctus, nibh lectus pellentesque magna, at egestas eros nisi sit amet lacus. In hac habitasse platea dictumst."
  es:
    language_name: Español
    description: "Únase a nosotros para el State of the Map LATAM 2024 en Belém, Brasil, del 7 al 8 de diciembre de 2024. Participe con expertos y entusiastas de toda Latinoamérica en esta conferencia vibrante dedicada a fomentar la cartografía abierta y las tecnologías geoespaciales innovadoras."
    modal:
      abstract: Ver resumen
      close: Cerrar
    menu:
      about:
        label: Acerca de
        url: /#about
      program:
        label: Programa
        url: /#program
      sponsors:
        label: Patrocinadores
        url: /#sponsors
      access:
        label: Cómo llegar
        url: /#access
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "La conferencia latinoamericana de OpenStreetMap"
      location: "Belém, Brasil"
      dates: "7 y 8 de diciembre, 2024"
      registrations_button: "Inscripciones"
      submit_proposal: "Envía tu Ponencia"
    venue_section:
      title: "Lugar"
      place_name: "Instituto Federal do Pará (IFPA)"
      description: "Vivamus aliquet dignissim sapien, semper venenatis massa sagittis dictum. Mauris in magna rutrum, tristique est quis, venenatis nisl. Sed quis nibh nulla. Praesent eu volutpat urna. Maecenas venenatis, augue sed aliquam luctus, nibh lectus pellentesque magna, at egestas eros nisi sit amet lacus. In hac habitasse platea dictumst."
  pt:
    language_name: Português
    description: "Junte-se a nós para o State of the Map LATAM 2024 em Belém, Brasil, de 7 a 8 de dezembro de 2024. Engaje com especialistas e entusiastas de toda a América Latina nesta conferência vibrante dedicada a fomentar o mapeamento aberto e tecnologias geoespaciais inovadoras."
    modal:
      abstract: Ver resumo
      close: Fechar
    menu:
      about:
        label: Sobre
        url: /pt/#about
      program:
        label: Programa
        url: /pt/#program
      sponsors:
        label: Patrocinadores
        url: /pt/#sponsors
      access:
        label: Como Chegar
        url: /pt/#access
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "A conferência latino-americana de OpenStreetMap"
      location: "Belém, Brasil"
      dates: "7 e 8 de dezembro de 2024"
      registrations_button: "Inscreva-se"
      submit_proposal: "Envie sua atividade"
    venue_section:
      title: "Local"
      place_name: "Instituto Federal do Pará (IFPA)"
      description: "Vivamus aliquet dignissim sapien, semper venenatis massa sagittis dictum. Mauris in magna rutrum, tristique est quis, venenatis nisl. Sed quis nibh nulla. Praesent eu volutpat urna. Maecenas venenatis, augue sed aliquam luctus, nibh lectus pellentesque magna, at egestas eros nisi sit amet lacus. In hac habitasse platea dictumst."
