# Site settings
title: State of the Map LATAM 2024
author: OpenStreetMap Latam
email: info@osmlatam.org
contact_form_url:
  pt: https://forms.gle/jgPoeGkrALZv5MJM7
  en: https://forms.gle/r3JXZsUNi5uxJ5Fj9
  es: https://forms.gle/aW3VLGV1B36dz4FF6
baseurl: ""
website: "https://2024.osmlatam.org"
exclude: [README.md]

social:
  mailing_list:
    title: "Mailing List"
    url: "https://lists.openstreetmap.org/listinfo/talk-latam"
    font_awesome_icon: "fa-envelope"
  telegram:
    title: "Telegram"
    url: "https://t.me/OSMLatam"
    font_awesome_icon: "fa-telegram"
  twitter:
    title: "Twitter"
    handle: "@osmlatam"
    url: "https://twitter.com/osmlatam"
    font_awesome_icon: "fa-twitter"
  github:
    title: "GitHub"
    url: "https://github.com/OSMLatam/sotm-latam-2024"
    font_awesome_icon: "fa-github"
  facebook:
    title: "Facebook"
    url: "https://www.facebook.com/osmlatam"
    font_awesome_icon: "fa-facebook"
  youtube:
    title: "YouTube"
    url: "https://www.youtube.com/channel/UCzYgQtCudy1ihZYAlpC3EXQ"
    font_awesome_icon: "fa-youtube"
  linkedin:
    title: "LinkedIn"
    url: "https://www.linkedin.com/company/103151706/"
    font_awesome_icon: "fa-linkedin"

registrations:
  open: true
  url: https://doity.com.br/sotm-latam-2024

program:
  # stage: call-for-proposals-will-open-soon
  # stage: call-for-proposals-open
  # stage: call-for-proposals-closed
  stage: program-is-ready
  url: "https://talks.osgeo.org/sotm2024-latam/talk/"

sponsorship_campaign_is_open: true

# Build settings
markdown: kramdown

# Venue
map_config:
  map_center: [-1.43797, -48.46028] # Latitude and Longitude
  marker_lat_lng: [-1.43848, -48.46025]
  zoom_level: 18

# Translations
t:
  en:
    language_name: English
    description: "Join the OpenStreetMap Latin American community in the Amazon city of Belém do Pará from December 6-8, 2024, to discuss projects, share ideas, and strengthen our network."
    modal:
      abstract: Abstract
      close: Close
    menu:
      program:
        label: Program
        url: /en/#program
      sponsors:
        label: Sponsors
        url: /en/#sponsors
      guide:
        label: Event Guide
        url: /en/event-guide
      blog:
        label: Blog
        url: https://blog.osmlatam.org
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "The Latin American OpenStreetMap Conference"
      location: "Belém, Brazil"
      dates: "December 6-8, 2024"
      registrations_button: "Register Now"
      submit_proposal: "Submit Your Proposal"
      view_program: "View Program"
    about_section:
      title: "About this event"
      description: "The State of the Map Latam 2024, hosted in Belém do Pará, is the sixth Latin American OpenStreetMap conference. The event, organized by the community, aims to bring together mappers, developers, researchers, and OpenStreetMap enthusiasts to share experiences, learn, and collaborate on the project."
    program_section:
      title: "Program"
      call_for_proposals_will_open_soon: "The call for activities will open soon!"
      call_for_proposals_open: "Call for proposals is open! We use Pretalx, a user-friendly conference management platform, to handle submissions and build our program. Submit your proposals!"
      submit_your_proposal: "Submit your proposal via Pretalx"
      thank_you_submissions: "The submission of proposals is closed. The program committee is reviewing the submissions and we will announce the program soon."
      program_is_finalized: "Our program is finalized! Check out the complete schedule on Pretalx to plan your conference experience."
      view_program: "View Program on Pretalx"
    sponsor_section:
      title: "Sponsors"
      thank_you_sponsors: "We thank all our sponsors for supporting the event!"
      campaign:
        invite: "Our sponsorship campaign is open! Become a sponsor and gain direct access to a vibrant community of IT professionals, geographers, students, and other industry experts."
        brochure_button: "Download the sponsorship brochure"
    contact_section:
      title: "Contact"
      description: "If you have any questions or need more information, please contact us."
      button_title: "Visit our contact form"

  es:
    language_name: Español
    description: "Únete a la comunidad de OpenStreetMap Latinoamérica en la ciudad amazónica de Belém do Pará, del 6 al 8 de diciembre de 2024, para discutir proyectos, compartir ideas y fortalecer nuestra red."
    modal:
      abstract: Ver resumen
      close: Cerrar
    menu:
      program:
        label: Programa
        url: /#program
      sponsors:
        label: Patrocinadores
        url: /#sponsors
      guide:
        label: Guía del Evento
        url: /guia-del-evento
      blog:
        label: Blog
        url: https://blog.osmlatam.org
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "La conferencia latinoamericana de OpenStreetMap"
      location: "Belém, Brasil"
      dates: "6, 7 y 8 de diciembre, 2024"
      registrations_button: "Inscripciones"
      submit_proposal: "Envía tu Ponencia"
      view_program: "Ver Programa"
    about_section:
      title: "Acerca de este evento"
      description: "El State of the Map Latam 2024, con sede en Belém do Pará, es la sexta conferencia latinoamericana de OpenStreetMap. El evento, organizado por la comunidad, tiene como objetivo reunir a cartógrafos, desarrolladores, investigadores y entusiastas de OpenStreetMap para compartir experiencias, aprender y colaborar en el proyecto."
    program_section:
      title: "Programa"
      call_for_proposals_will_open_soon: "¡La convocatoria de actividades se abrirá pronto!"
      call_for_proposals_open: "¡La convocatoria de propuestas está abierta! Utilizamos Pretalx, una plataforma amigable de gestión de conferencias, para manejar las presentaciones y construir nuestro programa. ¡Envía tus propostas!"
      submit_your_proposal: "Envía tu propuesta a través de Pretalx"
      thank_you_submissions: "El envío de propuestas ha terminado. El comité del programa está revisando las propuestas y pronto anunciaremos el programa."
      program_is_finalized: "¡Nuestro programa está finalizado! Consulta el cronograma completo en Pretalx para planificar tu experiencia en la conferencia."
      view_program: "Ver Programa en Pretalx"
    sponsor_section:
      title: "Patrocinios"
      thank_you_sponsors: "¡Agradecemos a todos nuestros patrocinadores por apoyar el evento!"
      campaign:
        invite: "¡Nuestra campaña de patrocinio está abierta! Conviértete en patrocinador y accede directamente a una comunidad vibrante de profesionales de TI, geógrafos, estudiantes y otros expertos del sector."
        brochure_button: "Descargue el folleto de patrocinio"
    contact_section:
      title: "Contacto"
      description: "Si tienes alguna pregunta o necesitas más información, por favor contáctanos."
      button_title: "Visita nuestro formulario de contacto"

  pt:
    language_name: Português
    description: "Reúna-se com a comunidade de OpenStreetMap da América Latina na cidade amazônica de Belém do Pará, de 6 a 8 de dezembro de 2024, para discutir projetos, compartilhar ideias e fortalecer nossa rede."
    modal:
      abstract: Ver resumo
      close: Fechar
    menu:
      program:
        label: Programa
        url: /pt/#program
      sponsors:
        label: Patrocinadores
        url: /pt/#sponsors
      guide:
        label: Guia do Evento
        url: /pt/guia-do-evento
      blog:
        label: Blog
        url: https://blog.osmlatam.org
    intro_section:
      alt_text: "State of the Map LATAM - Belém 2024"
      headline: "A conferência latino-americana de OpenStreetMap"
      location: "Belém, Brasil"
      dates: "6, 7 e 8 de dezembro de 2024"
      registrations_button: "Inscreva-se"
      submit_proposal: "Envie sua atividade"
      view_program: "Ver Programa"
    about_section:
      title: "Sobre este evento"
      description: "O State of the Map Latam 2024, sediado em Belém do Pará, é a sexta conferência latino-americana do OpenStreetMap. O evento, organizado pela comunidade, visa reunir mapeadores, desenvolvedores, pesquisadores e entusiastas do OpenStreetMap para compartilhar experiências, aprender e colaborar com o projeto."
    program_section:
      title: "Programa"
      call_for_proposals_will_open_soon: "A chamada de atividades será aberta em breve!"
      call_for_proposals_open: "A chamada de propostas está aberta! Usamos o Pretalx, uma plataforma amigável de gerenciamento de conferências, para lidar com as submissões e construir nosso programa. Envie suas proposta!"
      submit_your_proposal: "Envie sua proposta via Pretalx"
      thank_you_submissions: "O envio de propostas está encerrado. O comitê de programa está revisando as propostas e, em breve, divulgaremos o programa."
      program_is_finalized: "Nosso programa está finalizado! Veja o cronograma completo no Pretalx para planejar sua experiência na conferência."
      view_program: "Visualizar Programa no Pretalx"
    sponsor_section:
      title: "Patrocínios"
      thank_you_sponsors: "Agradecemos a todos os nossos patrocinadores por apoiar o evento!"
      campaign:
        invite: "Nossa campanha de patrocínio está aberta! Torne-se um patrocinador e tenha acesso direto a uma comunidade vibrante de profissionais de TI, geógrafos, estudantes e outros especialistas do setor."
        brochure_button: "Baixe o folder de patrocínio"
    contact_section:
      title: "Contato"
      description: "Se você tiver alguma dúvida ou precisar de mais informações, entre em contato conosco."
      button_title: "Visite nosso formulário de contato"
